version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:logql-regexp-0eb66ca-WIP3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  nginx:
    image: nginx:stable
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    ports:
      - "8080:80"
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./www:/usr/share/nginx/html
    networks:
      - loki

  grafana:
    image: grafana/grafana-enterprise-dev:master-cd0c4dbc-fb5f-4f85-9a42-a6c0ead7ca96
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./provisioning/dashboards/:/var/lib/grafana/dashboards/
    ports:
      - "3000:3000"
    networks:
      - loki

  hey1:
    image: ricoli/hey
    command: -m GET -z 7200h -c 1 -q 2 http://nginx/foo.html
    networks:
      - loki
  hey2:
    image: ricoli/hey
    command: -m PUT -z 7200h -c 1 -q 2 http://nginx/500.html
    networks:
      - loki
  hey3:
    image: ricoli/hey
    command: -m GET -z 7200h -c 1 -q 4 http://nginx/loki.jpeg
    networks:
      - loki
  hey4:
    image: ricoli/hey
    command: -m GET -z 7200h -c 1 -q 10 http://nginx/bar.html
    networks:
      - loki
  hey5:
    image: ricoli/hey
    command: -m POST -z 7200h -c 1 -q 2 http://nginx/buzz.html
    networks:
      - loki
  hey6:
    image: ricoli/hey
    command: -m GET -z 7200h -c 1 -q 4 http://nginx/buzz.html
    networks:
      - loki
